Revert "prevent duplicate minizip symbols if compiled under spring"
This reverts commit ff87f00f58626391d194385ae1d83cfb42afc7df.

this change broke linking of pr-downloader:

tools/pr-downloader/src/FileSystem/SevenZipArchive.cpp:122: error: undefined reference to 'LookToRead2_CreateVTable'